# Generated by Django 4.0.1 on 2022-02-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puljibsa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='votes',
        ),
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(default='', unique=True),
        ),
    ]
