# Generated by Django 4.0.1 on 2022-02-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puljibsa', '0002_remove_answer_votes_question_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(unique=True),
        ),
    ]
