# Generated by Django 4.0.1 on 2022-02-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puljibsa', '0004_remove_question_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
