# Generated by Django 4.0.1 on 2022-02-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puljibsa', '0009_plant_plt_enm_plant_plt_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plt_cd',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
