# Generated by Django 4.0.1 on 2022-02-22 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puljibsa', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plt_cd', models.IntegerField(unique=True)),
                ('plt_nm', models.CharField(max_length=100)),
                ('plt_water', models.TextField()),
                ('plt_amount_water', models.TextField()),
                ('plt_location', models.TextField()),
                ('plt_disease', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlantsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plt_status_content', models.TextField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puljibsa.answer')),
                ('plants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puljibsa.plants')),
            ],
        ),
    ]
