# Generated by Django 4.0.1 on 2022-02-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puljibsa', '0007_plants_plantsstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plants',
            new_name='Plant',
        ),
        migrations.RenameModel(
            old_name='PlantsStatus',
            new_name='PlantStatus',
        ),
    ]
