# Generated by Django 4.0.1 on 2022-02-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puljibsa', '0008_rename_plants_plant_rename_plantsstatus_plantstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plt_enm',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='plt_exp',
            field=models.TextField(default='NULL'),
            preserve_default=False,
        ),
    ]
