# Generated by Django 4.0.1 on 2022-02-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puljibsa', '0010_alter_plant_plt_cd'),
    ]

    operations = [
        migrations.CreateModel(
            name='PJSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_1', models.IntegerField()),
                ('answer_2', models.IntegerField()),
                ('answer_3', models.IntegerField()),
                ('answer_4', models.IntegerField()),
                ('user_pic', models.ImageField(blank=True, null=True, upload_to='puljibsa')),
            ],
        ),
    ]
